### ISSUE TITLE
pre trained

### ISSUE THREAD

**Issue by ganeshmanikanta** [psolanke/OpticalFlowDetection#1]
hello,

Thank you for your contribution. My question is do you have some thing which is pre trained model.I can download that model and use that model in the code provided to detect vehicle from drone videos
That could be great help
Thank you.

**Comment by fusang1337** [comment]
`Traceback (most recent call last):
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 168, in <module>
    main(sys.argv[1:])
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 164, in main
    show_video_loop_lk()
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 61, in show_video_loop_lk
    p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-jpmv6t9_/opencv/modules/video/src/lkpyramid.cpp:1260: error: (-215:Assertion failed) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function 'calc'`


`Traceback (most recent call last):
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 168, in <module>
    main(sys.argv[1:])
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 164, in main
    show_video_loop_lk()
  File "/home/thhicv/program/fr_use_prog/OpticalFlowDetection/preprocessing.py", line 70, in show_video_loop_lk
    mask = cv2.line(mask, (a,b),(c,d), color[i].tolist(), 2)
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type


进程已结束，退出代码为 1
`
